# No need to set modifyImagesWithDigest to `true` - this is the default
# behavior
signatures:
  - image: "ghcr.io/kubewarden/tests/pod-privileged:v0.2.1"
    certificates:
      # user-1
      - |
        -----BEGIN CERTIFICATE-----
        MIIC4jCCAoigAwIBAgIUbs96IMjvyz4tRsMa0qg2/1OS7nkwCgYIKoZIzj0EAwIw
        gZIxCzAJBgNVBAYTAkRFMRAwDgYDVQQIEwdCYXZhcmlhMRIwEAYDVQQHEwlOdXJl
        bWJlcmcxEzARBgNVBAoTCkt1YmV3YXJkZW4xIzAhBgNVBAsTGkt1YmV3YXJkZW4g
        SW50ZXJtZWRpYXRlIENBMSMwIQYDVQQDExpLdWJld2FyZGVuIEludGVybWVkaWF0
        ZSBDQTAeFw0yNDA5MDMxMTQ1MDBaFw0zNDA5MDExMTQ1MDBaMIGFMQswCQYDVQQG
        EwJERTEQMA4GA1UECBMHQmF2YXJpYTESMBAGA1UEBxMJTnVyZW1iZXJnMRMwEQYD
        VQQKEwpLdWJld2FyZGVuMRgwFgYDVQQLEw9LdWJld2FyZGVuIFVzZXIxITAfBgNV
        BAMTGHVzZXIxLmN1c3RvbS13aWRnZXRzLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
        AwEHA0IABOBfixg7oqG3qi4hU9edWYzWeVZlNH5ZFpFnHlrPbGSasRNXRx2Cpk3i
        10kAZYGVBuX/f1SmCMdJmYDhJdSd+6ijgcYwgcMwDgYDVR0PAQH/BAQDAgeAMCcG
        A1UdJQQgMB4GCCsGAQUFBwMCBggrBgEFBQcDAwYIKwYBBQUHAwEwDAYDVR0TAQH/
        BAIwADAdBgNVHQ4EFgQUti5Rcu7r3oYg/bgTzSj9bZ3jiPIwHwYDVR0jBBgwFoAU
        jywEuG6n1dObiNNpMe4juuz0k/cwHgYDVR0RBBcwFYETdXNlcjFAa3ViZXdhcmRl
        bi5pbzAaBgorBgEEAYO/MAEBBAxrdy1vd24taW5mcmEwCgYIKoZIzj0EAwIDSAAw
        RQIgNDLvuujteFtw/eqnTQAIoyuZWBftRm1E8NEl4oSP/VgCIQCQVAEO54EaRnFC
        tgeGtSI8hs/HKkFMC9b2p8xcODrv4g==
        -----END CERTIFICATE-----
    certificateChain:
      - |
        -----BEGIN CERTIFICATE-----
        MIICnzCCAkWgAwIBAgIUEUZi6i+0YpLZ6UWDXNSnnLnE+OEwCgYIKoZIzj0EAwIw
        gYIxCzAJBgNVBAYTAkRFMRAwDgYDVQQIEwdCYXZhcmlhMRIwEAYDVQQHEwlOdXJl
        bWJlcmcxEzARBgNVBAoTCkt1YmV3YXJkZW4xGzAZBgNVBAsTEkt1YmV3YXJkZW4g
        Um9vdCBDQTEbMBkGA1UEAxMSS3ViZXdhcmRlbiBSb290IENBMB4XDTI0MDkwMzEx
        NDUwMFoXDTM0MDkwMTExNDUwMFowgZIxCzAJBgNVBAYTAkRFMRAwDgYDVQQIEwdC
        YXZhcmlhMRIwEAYDVQQHEwlOdXJlbWJlcmcxEzARBgNVBAoTCkt1YmV3YXJkZW4x
        IzAhBgNVBAsTGkt1YmV3YXJkZW4gSW50ZXJtZWRpYXRlIENBMSMwIQYDVQQDExpL
        dWJld2FyZGVuIEludGVybWVkaWF0ZSBDQTBZMBMGByqGSM49AgEGCCqGSM49AwEH
        A0IABF4OTX6Kw8FMFXULP9/c6boHM9oE+ZHrE6bebAiPjBhzi/saUV/9Dpgsdc6G
        HcKcH0AWwq5uNOyR+Q1eM5ayykOjgYYwgYMwDgYDVR0PAQH/BAQDAgEGMB0GA1Ud
        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDAzASBgNVHRMBAf8ECDAGAQH/AgEAMB0G
        A1UdDgQWBBSPLAS4bqfV05uI02kx7iO67PST9zAfBgNVHSMEGDAWgBRgIvjfdnIb
        PyODtWDkkdntm72bOTAKBggqhkjOPQQDAgNIADBFAiEAzjzAezO/VCOxLZY1yhUR
        CZ/Byo5oDs9CLKManGwdMVgCIHV6f4HD+2cfFRlBP3qQ4nFjTV92a2rylPZs+kWe
        yI2G
        -----END CERTIFICATE-----
      - |
        -----BEGIN CERTIFICATE-----
        MIICSzCCAfCgAwIBAgIUeHODG4wLrVR3GGc2XdJ1jxhhrKQwCgYIKoZIzj0EAwIw
        gYIxCzAJBgNVBAYTAkRFMRAwDgYDVQQIEwdCYXZhcmlhMRIwEAYDVQQHEwlOdXJl
        bWJlcmcxEzARBgNVBAoTCkt1YmV3YXJkZW4xGzAZBgNVBAsTEkt1YmV3YXJkZW4g
        Um9vdCBDQTEbMBkGA1UEAxMSS3ViZXdhcmRlbiBSb290IENBMB4XDTI0MDYyODEy
        MzkwMFoXDTI5MDYyNzEyMzkwMFowgYIxCzAJBgNVBAYTAkRFMRAwDgYDVQQIEwdC
        YXZhcmlhMRIwEAYDVQQHEwlOdXJlbWJlcmcxEzARBgNVBAoTCkt1YmV3YXJkZW4x
        GzAZBgNVBAsTEkt1YmV3YXJkZW4gUm9vdCBDQTEbMBkGA1UEAxMSS3ViZXdhcmRl
        biBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbZC14QCsJn+bfsqD
        OMVNyc+x7+6mXs1ZEn/YopZxv+3YY9aSrIX//2CwLsOyLmTsSOrYBr5rl2lB7i51
        BSaR/aNCMEAwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0O
        BBYEFGAi+N92chs/I4O1YOSR2e2bvZs5MAoGCCqGSM49BAMCA0kAMEYCIQC0axTr
        1sQlQzREfsI6T7HH07rM72sPhxdFSkUtUY7rUgIhAM0CD1H04MOpxI1OM2q4rEdt
        u9SiL56Dr6/wahCpGQ5e
        -----END CERTIFICATE-----
    requireRekorBundle: true
